#!/bin/bash 

# This script is run after a git-commit.  It is executed every time 'git commit' is executed
# Currently, this script checks the status of the current branch and prompts
# the user to track their branch if it is untracked and to push if >10 unpushed commits
# exist.
# if additional precommit functionality is requested, it should be added to this script.
#
# This script is inserted in the .git/hooks directory of repositories setup with
# configure_rosetta_repo.sh

#is the current 
git rev-parse --symbolic-full-name git_hooks@{u} > /dev/null
