#!/bin/sh 

# This script is run before a git-commit.  It is executed every time 'git commit' is executed
# Currently, this script checks for large incoming files and prompts the user for confirmation
# if additional precommit functionality is requested, it should be added to this script.
#
# non-zero status exits will abort the commit, status of zero will continue.
# This script is inserted in the .git/hooks directory of repositories setup with
# configure_rosetta_repo.sh