/* Header for module maxd_toolbox, generated by p2c */
#ifndef MAXD_TOOLBOX_H
#define MAXD_TOOLBOX_H


#ifdef MAXD_TOOLBOX_G
# define vextern
#else
# define vextern extern
#endif
/*
__________________________________________________________________________

This set of programs constructs full atomic coordinates of a protein
from a given C(alpha) trace and optimizes side chain geometry.

Copyright by Liisa Holm and Chris Sander, 1989-1991.

No redistribution, no program changes, no commercial use.

For details, see J.Mol.Biol. 218, 183-194 (1991).

___________________________________________________________________________
*/
/* array dimensioning constants */


#undef vextern

#endif /*MAXD_TOOLBOX_H*/

/* End. */
