#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Simple class to keep track of external citations and report them while using mhc_energy_tools

@author: Chris Bailey-Kellogg, cbk@cs.dartmouth.edu; Brahm Yachnin, brahm.yachnin@rutgers.edu 
"""

class Citation ():
    """Stores the information for a particular citation"""
    
    def set_reference_text(self, reference = ""):
        """Set the reference/citation text for this citation."""
        self.reference = reference
    
    def used_citation(self):
        """Indicate that we've used the citation.  Note that it shouldn't be possible to not use the citation."""
        self.used = True
    
    def print_citation_info(self):
        """Print out the citation data for this particular citation, if true."""
        #Do nothing if used is false
        if not self.used: return
        
        print("You have used " + self.name + ".  This reference should be cited if used in publication.")
        print(self.reference)
    
    def __init__(self, name = "", used = False, reference = ""):
        """name: The name of the resource being cited
        used: Bool that tracks if a citation has been used yet
        reference: Actual text containing reference information"""
        self.name = name
        self.used = used
        self.reference = reference

class CitationTracker ():
    """Tracks citation data and allows for it to be reported as necessary."""
    
    #Create Citation class variables for each citation type
    #TODO: When our stuff is published, add it to this list and to the citation_list below
    #mhc_epitope_energy = Citation("MHCEpitopeEnergy tools", used = True)
    propred = Citation("ProPred")
    netmhcii = Citation("NetMHCII")
    iedb = Citation("the IEDB database")
    
    #Set the citation text for each Citation
    propred.set_reference_text(
        """        Matrices obtained from http://crdd.osdd.net/raghava/propred/
        If you use results based on these predictions, please cite
        Singh, H. and Raghava, G.P.S. (2001) ProPred: Prediction of DR binding sites. Bioinformatics, 17(12):1236-37.
        http://www.ncbi.nlm.nih.gov/pubmed/11751237"""
        )
    netmhcii.set_reference_text(
        """        Improved methods for predicting peptide binding affinity to MHC class II molecules.
        Jensen KK, Andreatta M, Marcatili P, Buus S, Greenbaum JA, Yan Z, Sette A, 
        Peters B, Nielsen M.   
        Immunology. 2018 Jan 6. doi: 10.1111/imm.12889."""
        )
    iedb.set_reference_text(
        """        Citing the IEDB
        Users are requested to cite the IEDB when they present information obtained from the IEDB: http://www.iedb.org. The journal
        reference for the IEDB was updated in 2018 and should be cited as: Vita R, Mahajan S, Overton JA, Dhanda SK, Martini S,
        Cantrell JR, Wheeler DK, Sette A, Peters B. The Immune Epitope Database (IEDB): 2018 update. Nucleic Acids Res. 2019 Jan
        8;47(D1):D339-D343. doi: 10.1093/nar/gky1006. PMID: 30357391

        All publications or presentations referring to data generated by use of the IEDB Resource Analysis tools should include
        citations to the relevant reference(s), found at http://tools.iedb.org/main/references/"""
        )
    
    #And a list of the citation types
    citation_list = [propred, netmhcii, iedb]

    def add_citation(self, citation):
        """Flag a particular citation as being used.  Note that you shouldn't be able to set it back to false."""
        citation.used_citation()
    
    def output_citations(self, citation_list = citation_list):
        """Loop over the citations in citation_list and output their info, if needed."""
        for citation in citation_list:
            citation.print_citation_info()

    def __init__(self):
        """
        """