#!/bin/bash

ROOT=/local/luki/clang

cd $ROOT/build

# ninja rosetta-refactor-tool

/usr/bin/clang++   -DCLANG_ENABLE_ARCMT -DCLANG_ENABLE_REWRITER -DCLANG_ENABLE_STATIC_ANALYZER -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -fcolor-diagnostics -fdata-sections -fno-common -Woverloaded-virtual -Wcast-qual -fno-strict-aliasing -Wno-nested-anon-types -O3 -DNDEBUG -Itools/clang/tools/extra/rosetta-refactor-tool -I$ROOT/llvm/tools/clang/tools/extra/rosetta-refactor-tool -I$ROOT/llvm/tools/clang/include -Itools/clang/include -Iinclude -I$ROOT/llvm/include    -fno-exceptions -fno-rtti -MMD -MT tools/clang/tools/extra/rosetta-refactor-tool/CMakeFiles/rosetta-refactor-tool.dir/RosettaTool.cpp.o -MF "tools/clang/tools/extra/rosetta-refactor-tool/CMakeFiles/rosetta-refactor-tool.dir/RosettaRewriter.cpp.o.d" -o tools/clang/tools/extra/rosetta-refactor-tool/CMakeFiles/rosetta-refactor-tool.dir/RosettaRewriter.cpp.o -c $ROOT/llvm/tools/clang/tools/extra/rosetta-refactor-tool/RosettaRefactorTool.cpp \
&& \
/usr/bin/clang++   -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -fcolor-diagnostics -fdata-sections -fno-common -Woverloaded-virtual -Wcast-qual -fno-strict-aliasing -Wno-nested-anon-types -O3 -DNDEBUG  -Wl,--gc-sections tools/clang/tools/extra/rosetta-refactor-tool/CMakeFiles/rosetta-refactor-tool.dir/RosettaRewriter.cpp.o  -o bin/rosetta-refactor-tool  lib/libLLVMSupport.a lib/libclangAST.a lib/libclangASTMatchers.a lib/libclangBasic.a lib/libclangFrontend.a lib/libclangTooling.a lib/libclangASTMatchers.a lib/libclangFrontend.a lib/libclangParse.a lib/libLLVMMCParser.a lib/libclangSerialization.a lib/libclangSema.a lib/libclangEdit.a lib/libclangAnalysis.a lib/libclangDriver.a lib/libLLVMOption.a lib/libLLVMTransformUtils.a lib/libLLVMipa.a lib/libLLVMAnalysis.a lib/libLLVMTarget.a lib/libclangRewriteCore.a lib/libclangAST.a lib/libclangLex.a lib/libclangBasic.a lib/libLLVMMC.a lib/libLLVMObject.a lib/libLLVMBitReader.a lib/libLLVMCore.a lib/libLLVMSupport.a -lrt -ldl -ltinfo -lpthread -lz -Wl,-rpath,"\$ORIGIN/../lib"
